---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt


additional_build_steps:
  prepend:
  - COPY ./group_vars /home/runner/group_vars/
  - COPY ./ansible.cfg /home/runner/ansible.cfg
  - COPY ./scripts /home/runner/scripts/
  append:
  - RUN curl -sSL https://sdk.cloud.google.com | bash
  - ENV PATH $PATH:/home/runner/google-cloud-sdk/bin
  - RUN $(gcloud info --format="value(basic.python_location)") -m pip install numpy
  - WORKDIR /home/runner